# This workflow builds transbase-python distributions for windows, macos and linux and uploads it to https://pypi.org/
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python Publish

on:
  push:
    tags:
      - "v*.*.*" # when tag with name 'vX.Y.Z' is pushed to master
  release:
    types: [published] # or when a new Release is created&published in GH web interface
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests setuptools wheel
          python setup.py get_lib
      - name: Build Linux 📦
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: python setup.py sdist bdist_wheel --plat-name manylinux_2_34_x86_64
      - name: Build Windows and Mac 📦
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: python setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: "release"
          path: dist/

  publish:
    # This is a separate job, as the upload must run only once, after all wheels have been created.
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: release
          path: dist/
      - name: Publish 📦 to TestPyPI
        #if: contains(github.ref, 'rc')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: ./dist/
      - name: Publish 📦 to PyPI if tagged
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ./dist/
